# Generated by Django 3.2.9 on 2021-11-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('short_path', models.CharField(default='', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hits', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
