# Generated by Django 3.2.9 on 2021-12-10 14:23

from django.db import migrations, models
import urlshorten.models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshorten', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmapper',
            name='short_path',
            field=models.CharField(default=urlshorten.models.UrlMapper._generate_rand_str, max_length=6, unique=True),
        ),
    ]
